#配置Server基本属性
server:
  port: 8887
  servlet:
    context-path: /csu_super_mall #配置上下文路径，当前路径为本地路径

#配置JDBC属性
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tmall_springboot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      database: mysql
      # 启动时会根据实体类生成表，当实体类属性变动的时候，表结构也会更新
      ddl-auto: update
      #jpa对实体类的默认字段会把驼峰命名的属性，转换为字段名的时候自动加上下划线。 这个配置的作用就是去掉下划线
      #比如属性名称是 createDate, jpa 默认转换为字段名 create_Date。 有了这个配置之后，就会转换为同名字段 createDate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # 控制台显示SQL
    show-sql: true

  #整合redis
  redis:
    host: 127.0.0.1
    #    host: 192.168.31.247
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 1000
        max-idle: 500
        max-wait: 500
    timeout: 5000

  cache:
    type: redis

  elasticsearch:
    rest:
      uris: http://localhost:9200
